### ISSUE TITLE
Error while training yolov4tiny

### ISSUE THREAD

**Issue by abpanchal95** [Adeel-Intizar/Xtreme-Vision#2]
/.local/lib/python3.8/site-packages/xtreme_vision/Detection/yolov4/tf/dataset.py", line 198, in bboxes_to_ground_truth
    ground_truth[i][0, _y, _x, j, 0:4] = xywh

IndexError: index 20 is out of bounds for axis 1 with size 20

	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_train_function_14598]

Function call stack:
train_function

**Comment by Adeel-Intizar** [comment]
can you share your script and data
