### ISSUE TITLE
Can this code work using conda environment?

### ISSUE THREAD

**Issue by zaheerbeg21** [Adeel-Intizar/Xtreme-Vision#8]
i am facing issue when i try  to install xtreme-vision packages using conda ..My OS is wondows 10. I want to run code using GPU ..
[conda tnstall attempt](https://user-images.githubusercontent.com/65087774/102197061-ab2a2c00-3ee6-11eb-8ba2-702412574a4b.JPG)

**Comment by Adeel-Intizar** [comment]
Create a virtual environment, either with pip or conda, 
activate that venv and try to use python 3.6
and just type "pip install xtreme-vision" inside that venv

It should install it easily
